name: animated_sidebar
description: A collapsable sidebar plugin for Flutter, optimized for web and desktop applications.
version: 1.0.0
homepage: https://github.com/kesimo/animated_sidebar
repository: https://github.com/kesimo/animated_sidebar

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
